config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #Crear la ruta '/todos' que apunte al método todos#index con el verbo get.
  #Crear la ruta 'todos/new' con el verbo get.
  #Crear la ruta '/todos' que apunte al método todos#create con el verbo post.
  #Crear la ruta '/todos/:id' que apunte al método todos#show con el verbo get y el prefijo todo.
  #Crear la ruta '/todos/:id/edit' que apunte al método todos#edit con el verbo get.
  #Crear la ruta '/todos/:id' que apunte al método todos#update con el verbo patch.
  #Crear la ruta '/todos/:id' que apunte al método todos#destroy con el verbo delete.
  #Crear la ruta '/todos/:id/complete' que apunte al método todos#complete con el verbo get.

  get '/todos', to: 'todos#index'
  get '/todos/new'
  get 'todos/list'
  post '/todos', to: 'todos#create'
  get '/todos/:id', to:'todos#show', as: 'todo'
  get '/todos/:id/edit', to:'todos#edit', as: 'editar'
  patch '/todos/:id', to: 'todos#update'
  delete '/todos/:id', to: 'todos#destroy'
  get '/todos/:id/complete', to: 'todos#complete', as: 'complete'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
	validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
	before_action :find_todo, only: [:show, :edit, :update, :destroy, :complete]

	def index
		@todos = Todo.all
	end

	def new
		@todo = Todo.new
	end

	def create
		@todo = Todo.new(todo_params)
		@todo.save
		redirect_to todos_path
	end

	def show
	end

	def edit
	end

	def update
		@todo.update(todo_params)
		redirect_to todos_path
	end

	def destroy
		@todo.destroy
		redirect_to todos_path		
	end
	
	def complete
		@todo.completed = true
   		@todo.save
   		redirect_to todos_path
	end
	
	def list
		@todos = Todo.all
	end
	
	private
	def todo_params
		params.require(:todo).permit(:description, :completed)
	end
	
	def find_todo
		@todo = Todo.find(params[:id])
	end
end



#En el controller todos crear el método index. En este método se debe declarar una 
#variable de instancia @todos que almacenará la colección de ToDos existentes.
#En el controller todos crear el método show. Este método debe buscar un ToDo en base 
#al parámetro 'id'. (Todo.find) y asignarlo a a la variable @todo

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script
  		src="https://code.jquery.com/jquery-3.2.1.min.js"
  		integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
  		crossorigin="anonymous">
  	</script>
  	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

	<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>

  <body>
  	<nav class="navbar navbar-default">
        <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
              	<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
             	</button>
             	<a class="navbar-brand" href="#">Todos</a>
            </div>


            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav">

                <li><%= link_to "Index", todos_path %></li>
                <li><%= link_to "List", todos_list_path %></li>
                <li><%= link_to "New", todos_new_path %></li>

              </ul>

              <ul class="nav navbar-nav navbar-right">

              </ul>
            </div><!-- /.navbar-collapse -->
          </div><!-- /.container-fluid -->
        </nav>
    <div class="container-fluid">
    	<%= yield %>
    </div>
  </body>
</html>

app/views/todos/_form.html.erb
<div class="container">
<div class="row">
<div class="col-lg-10">
<div class="well">

	<%= form_with model: @todo, local: true do |t| %>
		<%= t.label :description, "Descripción" %>
		<%= t.text_field :description %>
	    <br><br>
		<%= t.label :completed, "Completado" %>
	    <%= t.select :completed, options_for_select([["si", true], ["no", false]])%>
	    <br><br>
	    <%= t.submit "Enviar" %>
	<% end %>
</div>
</div>
</div>
</div>

app/views/todos/complete.html.erb
<h1>lista</h1>
<br>
<div class="well">
	<h3> <%= @todo.description %></h3>
	<p> <%= @todo.completed %></p>
	<p> Creado hace: <%= time_ago_in_words @todo.created_at %></p>
</div>

app/views/todos/edit.html.erb
<h1>Editar</h1>
<br>
<%= render 'form' %>

app/views/todos/index.html.erb
<h1>Formulario</h1>
<br>
<p> <%= link_to "Crear", todos_new_path %> </p>
<% @todos.each do |todos| %>
	<div class="well">
		<h3> <%= todos.description %></h3>
		<p> <%= todos.completed %></p>
		<p>completed:
			<%
              if todos.completed
                flag = "checked"
              else
                flag = ""
              end
            %>
            <input type="checkbox" aria-label="" <%= flag %>  >
		</p>

		<p> <%= link_to "Ver", todos %></p>
		<p><%= link_to 'Editar', editar_path(todos) %> </p>
		<p> <%= link_to "Borrar", todos, method: :delete %> </p>
		<p> <%= link_to "Completar", complete_path(todos)%> </p>
	</div>
<% end %>

app/views/todos/list.html.erb
<div class="container">

  <h1>Listado</h1>

  <div class="row">

      <div class="col-lg-6">
        <div class="well"><b>Tareas Incompletas</b></div>
        <% @todos.each do |todos| %>
            <% if !todos.completed %>
              <div class="well"><%= todos.description %></div>
            <% end %>
        <% end %>
      </div>
    <div class="col-lg-6">
        <div class="well"><b>Tareas Completas</b></div>
			<% @todos.each do |todos| %>
            	<% if todos.completed %>
              	<div class="well"><%= todos.description %></div>
            <% end %>
        <% end %>
     </div>

    </div><!-- /.row -->


</div>

app/views/todos/new.html.erb
<h1>Nuevo</h1>
<br>
<%= render 'form' %>

app/views/todos/show.html.erb
<h1>Detalle</h1>
<br>
<div class="well">
	<h3> <%= @todo.description %></h3>
	<p> <%= @todo.completed %></p>
	<p> Creado hace: <%= time_ago_in_words @todo.created_at %></p>
</div>